### ISSUE TITLE
waason.ansible_bloatware does not match in example playbook and install command

### ISSUE THREAD

**Issue by LinforPros** [waason/ansible.bloatware#1]
README show the folowing:
Installation
ansible-galaxy install waason.bloatware

# ansible-galaxy install waason.bloatware
- downloading role 'bloatware', owned by waason
 [WARNING]: - waason.bloatware was NOT installed successfully: - sorry, waason.bloatware was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

DETAILS has the correct line:
Installation	$ ansible-galaxy install waason.ansible_bloatware

But the the example playbook suggests:
- hosts: all
  roles:
     - waason.bloatware

which is not right since it gets a different name in the search path:
 ls ~/.ansible/roles/ -1
waason.ansible_bloatware

Regards
Lin

**Comment by sbaerlocher** [comment]
@LinforPros Thank you for your issues, there was a bug with the name by importing in the Galaxy, I fix it. You find the role below: https://galaxy.ansible.com/waason/bloatware/

Regards
Simon
